Replace tab indent in shell script by space

diff --git a/install/cdr-stats-socketio b/install/cdr-stats-socketio
--- a/install/cdr-stats-socketio
+++ b/install/cdr-stats-socketio
@@ -17,76 +17,76 @@ SOCKETIO_SERVER_PIDFILE=$PID_PREFIX/cdr-stats-socketio-server.pid
 
 do_help()
 {
-	echo
-	echo "$(basename $0) (start|stop|restart|status|reload)"
-	echo
-	exit 1;
+    echo
+    echo "$(basename $0) (start|stop|restart|status|reload)"
+    echo
+    exit 1;
 }
 
 do_installerror()
 {
-	echo
-	echo "Error : We cannot locate the file $SOCKETIO_SERVER"
-	echo
-	exit 1;
+    echo
+    echo "Error : We cannot locate the file $SOCKETIO_SERVER"
+    echo
+    exit 1;
 }
 
 do_start()
 {
-	NICE=$(which nice)
-	server_already_running="false"
-	$VENV_OFF &>/dev/null
-	source $VENV_ON
+    NICE=$(which nice)
+    server_already_running="false"
+    $VENV_OFF &>/dev/null
+    source $VENV_ON
 
-	kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
-	if [ $? -eq 0 ]; then
-		echo "$SERVER_NAME already running"
-		server_already_running="true"
-	else
-		$NICE $SOCKETIO_SERVER -d -p $SOCKETIO_SERVER_PIDFILE start
-	fi
+    kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
+    if [ $? -eq 0 ]; then
+        echo "$SERVER_NAME already running"
+        server_already_running="true"
+    else
+        $NICE $SOCKETIO_SERVER -d -p $SOCKETIO_SERVER_PIDFILE start
+    fi
 
-	if [ "$server_already_running" = "true" ]; then
-		$VENV_OFF &>/dev/null
-		exit 0
-	fi
+    if [ "$server_already_running" = "true" ]; then
+        $VENV_OFF &>/dev/null
+        exit 0
+    fi
 
-	sleep 1s
-	if [ "$server_already_running" = "false" ]; then
-		kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null \
-			&& echo "$SERVER_NAME started" || echo "$SERVER_NAME start failed"
-	fi
-	$VENV_OFF &>/dev/null
+    sleep 1s
+    if [ "$server_already_running" = "false" ]; then
+        kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null \
+            && echo "$SERVER_NAME started" || echo "$SERVER_NAME start failed"
+    fi
+    $VENV_OFF &>/dev/null
 }
 
 
 do_stop()
 {
-	kill -TERM $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
-	if [ $? -eq 0 ]; then
-		echo "$SERVER_NAME stopped"
-		rm -f $SOCKETIO_SERVER_PIDFILE
-	else
-		echo "$SERVER_NAME stopping failed"
-	fi
+    kill -TERM $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
+    if [ $? -eq 0 ]; then
+        echo "$SERVER_NAME stopped"
+        rm -f $SOCKETIO_SERVER_PIDFILE
+    else
+        echo "$SERVER_NAME stopping failed"
+    fi
 }
 
 do_reload()
 {
-	kill -HUP $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
-	if [ $? -eq 0 ]; then
-		echo "$SERVER_NAME reloaded"
-	else
-		echo "$SERVER_NAME reload failed"
-	fi
+    kill -HUP $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null
+    if [ $? -eq 0 ]; then
+        echo "$SERVER_NAME reloaded"
+    else
+        echo "$SERVER_NAME reload failed"
+    fi
 }
 
 
 do_status()
 {
     echo "status..."
-	kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null \
-		&& echo "$SERVER_NAME running" || echo "$SERVER_NAME not running"
+    kill -0 $(cat $SOCKETIO_SERVER_PIDFILE 2>/dev/null) 2>/dev/null \
+        && echo "$SERVER_NAME running" || echo "$SERVER_NAME not running"
 }
 
 
@@ -100,26 +100,26 @@ SERVER_NAME="CDR-Stats-SocketIO-Server"
 
 case $1 in
 start)
-	do_start
+    do_start
 ;;
 
 stop)
-	do_stop
+    do_stop
 ;;
 
 restart)
-	do_stop
-	sleep 0.5s
-	do_start
+    do_stop
+    sleep 0.5s
+    do_start
 ;;
 
 status)
-	do_status
+    do_status
 ;;
 reload)
-	do_reload
+    do_reload
 ;;
 *)
-	do_help
+    do_help
 ;;
 esac
